# Generated by Django 6.1 on 2026-09-13 11:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=250)),
                ('project_desc', models.TextField()),
                ('ext_link_provided', models.BooleanField()),
                ('ext_link', models.URLField()),
            ],
        ),
    ]
