# Generated by Django 6.1 on 2026-09-12 22:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('short_desc', models.CharField(blank=True, max_length=250)),
                ('skill_category', models.CharField(choices=[('softskill', 'Softskill'), ('hardskill', 'Hardskill')])),
            ],
        ),
    ]
