# Generated by Django 6.1 on 2026-09-12 08:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year_start', models.CharField(default='Present', max_length=7)),
                ('year_end', models.CharField(default='Present', max_length=7)),
                ('institution_name', models.CharField(max_length=250)),
                ('activities', models.JSONField(default=['N', 'o', ' ', 'A', 'c', 't', 'i', 'v', 'i', 't', 'i', 'e', 's', ' ', 'h', 'a', 'v', 'e', ' ', 'b', 'e', 'e', 'n', ' ', 'a', 'd', 'd', 'e', 'd', ' ', ':', '('], null=True)),
            ],
        ),
    ]
