# Generated by Django 6.1 on 2026-09-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='activities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
