# Generated by Django 6.1 on 2026-09-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='media',
            field=models.ImageField(default='no_image_square.png', null=True, upload_to=''),
        ),
    ]
