# Generated by Django 6.1 on 2026-09-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_experience_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='responsibilities_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateField(auto_now=True),
        ),
    ]
