# Generated by Django 6.1 on 2026-09-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='media',
            field=models.FileField(default='no_image_square.png', null=True, upload_to=''),
        ),
    ]
