# Generated by Django 6.1 on 2026-09-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_experience_responsibilities_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
