# Generated by Django 6.1 on 2026-09-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_media_type_alter_project_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='media',
            field=models.FileField(default='no_image_square.png', null=True, upload_to='project-media/'),
        ),
    ]
