# Generated by Django 6.1 on 2026-09-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_education_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='institution_logo',
            field=models.ImageField(default='no_image_square.png', upload_to='institution_logo/'),
        ),
    ]
