# Generated by Django 6.1 on 2026-09-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_experience_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='place',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
