# Generated by Django 6.1 on 2026-09-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill'),
        ('main', '0005_alter_project_media'),
        ('main', '0005_education_institution_logo'),
        ('main', '0005_experience_place_alter_experience_title'),
    ]

    operations = [
    ]
