# Generated by Django 6.1 on 2026-09-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_merge_20260914_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='highlight_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('game project', 'Game Project'), ('ai project', 'AI Project'), ('web project', 'Web Project')], default='game project'),
        ),
        migrations.AddField(
            model_name='skill',
            name='highlight_skill',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
