# Generated by Django 6.1 on 2026-09-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project_highlight_project_project_project_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='highlite_experience',
            field=models.BooleanField(default=False),
        ),
    ]
