# Generated by Django 6.1 on 2026-09-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_experience_highlite_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='highlite_experience',
            new_name='highlight_experience',
        ),
    ]
