# Generated by Django 5.2.17 on 2026-09-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_highlite_experience_experience_highlight_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='activities',
            field=models.TextField(blank=True, default=''),
        ),
    ]
