# Generated by Django 5.2.17 on 2026-09-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_education_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('game_project', 'Game Project'), ('ai_project', 'AI Project'), ('web_project', 'Web Project')], default='game project'),
        ),
    ]
