# Generated by Django 5.2.17 on 2026-09-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_education_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='responsibilities_list',
            field=models.TextField(),
        ),
    ]
