# Generated by Django 5.2.17 on 2026-09-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('game project', 'Game Project'), ('ai project', 'AI Project'), ('web project', 'Web Project')], default='game project'),
        ),
    ]
