# Generated by Django 5.2.17 on 2026-09-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_experience_responsibilities_list'),
        ('main', '0012_alter_project_project_type'),
    ]

    operations = [
    ]
