# Generated by Django 5.2.17 on 2026-09-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_merge_20260921_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ext_link',
            field=models.URLField(blank=True),
        ),
    ]
