# Generated by Django 5.2.17 on 2026-09-27 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_project_ext_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stared_by',
            field=models.ManyToManyField(blank=True, related_name='starred_project', to=settings.AUTH_USER_MODEL),
        ),
    ]
