# Generated by Django 5.2.17 on 2026-09-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_project_stared_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='stared_by',
            new_name='starred_by',
        ),
    ]
