# Generated by Django 5.2.17 on 2026-10-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_experience_starred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='media',
            field=models.FileField(null=True, upload_to='project-media/'),
        ),
    ]
