# Generated by Django 5.2.17 on 2026-10-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_project_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='project-media/'),
        ),
    ]
